# Introduction

In this lab, we will learn about the `attempt` function in JavaScript. The `attempt` function allows us to invoke a function with the provided arguments and return either the result or an appropriate error object. We will explore the use of `try...catch` block to handle errors and create new `Error` objects if needed.
